name: cicd-pipeline
on:
  push:

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
      - name: Get dependencies
        run: npm install
      - name: Check format
        run: npm run check-format
      - name: Test
        run: npm test
